dir STI\carrot01.* /W
dir STI\clipboard.* /W
dir STI\dustpan.* /W
dir STI\gluetube.* /W
dir STI\interlockingbuildingblock03b.* /W
dir STI\keychain.* /W
dir STI\leek.* /W
dir STI\measuringspoon.* /W
dir STI\mitten04.* /W
dir STI\nail.* /W
dir STI\pictureframe04.* /W
dir STI\seashell01.* /W
dir STI\stapler03a.* /W
dir STI\tongs01b.* /W
dir STI\toydinosaur.* /W
dir STI\fork.* /W
dir STI\hat.* /W
dir STI\shoe.* /W
dir STI\razor01.* /W
dir STI\waterbottle01b.* /W
dir STI\bed-2.* /W
dir STI\cooler01.* /W
dir STI\dentalfloss03b.* /W
dir STI\woodboard.* /W
dir STI\cow.* /W
dir STI\church.* /W
dir STI\024-tonneau_barrel.* /W
dir STI\fryingpan02a.* /W
dir STI\weight01.* /W
dir STI\wheel01.* /W
dir STI\filmroll.* /W
dir STI\pill.* /W
dir STI\screwdriver04b.* /W
dir STI\candle08b.* /W
dir STI\earring01.* /W
dir STI\ribbon04.* /W
dir STI\scrubbingbrush05b.* /W
dir STI\solderingiron.* /W
dir STI\spatula04.* /W
dir STI\staple.* /W
dir STI\usbkey.* /W