copy D:\POOL\bed-2.*                                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\cruiseship.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\gardenutilityvehicle.*                  D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\locomotive.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\sailboat.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\fridge.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\uprightpiano01.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\cooler01.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\dentalfloss03b.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\fryingpan02a.*                          D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\woodboard.*                             D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\201-motard_motorcyclist.*               D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\294-ventilateur_fan.*                   D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\035-bibliotheque_book-shelves.*         D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\260-sapin_fir-tree.*                    D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\282-tractopelle_digger.*                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\tv.*                                    D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\briefcaseclosed.*                       D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\faucet.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\laptopopen.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\chair.*                                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\umbrellaopen.*                          D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\cow.*                                   D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\church.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\airhockeytable.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\barn.*                                  D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\bed.*                                   D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\boxtrailer.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\castle.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\castletower.*                           D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\cherrypicker.*                          D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\dryingmachine02.*                       D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\ferry.*                                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\forklift.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\freighttruck.*                          D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\grandpiano.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\hangar.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\lighthouse.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\mattress.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\293-usine_factory.*                     D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\weight01.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\wheel01.*                               D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\frenchfries.*                           D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\filmroll.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\pill.*                                  D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\screwdriver04b.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\156-hot-dog_hot-dog.*                   D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\kiwi03.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\rubikcube.*                             D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\strap.*                                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\candle08b.*                             D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\earring01.*                             D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\ribbon04.*                              D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\scrubbingbrush05b.*                     D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\slidetray.*                             D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\solderingiron.*                         D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\spatula04.*                             D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\staple.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\stickytack.*                            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\usbkey.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\034-biberon_feeding-bottle.*            D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\041-bonbon_candy.*                      D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\078-cassette_cassette.*                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\166-klaxon_horn.*                       D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\lobsteralive.*                          D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\flower.*                                D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\bridgestick.*                           D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\001-peche_peach.*                       D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\003-agrafeuse_stapler.*                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\010-anneaux_rings.*                     D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\039-ble_wheat.*                         D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\042-bonnet_cap.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\047-bouee_lifebuoy.*                    D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\048-boule_(pool)-ball.*                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\061-calculatrice_calculator.*           D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\065-couteau-suisse_swiss-army-k.*       D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\066-canne_cane.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\072-pendule_clock.*                     D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\076-cartouche_cartridge.*               D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\090-cible_dart-board.*                  D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\094-classeur_box-file.*                 D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\105-crevette_shrimp.*                   D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI
copy D:\POOL\111-dent_tooth.*                        D:\core\Research\projects\Embodied\EXPDATA\ActionObject\2016_Simulation\NSTI