move POOL\020-baignoire_bathtub.*                         STI\
move POOL\couch.*                                           STI\
move POOL\rocker.*                                          STI\
move POOL\178-locomotive_locomotive.*                     STI\
move POOL\008-ambulance_ambulance.*                       STI\
move POOL\064-camping-car_camper.*                        STI\
move POOL\018-car_bus.*                                   STI\
move POOL\car.*                                             STI\
move POOL\piano.*                                           STI\
move POOL\truck.*                                           STI\
move POOL\plane.*                                           STI\
move POOL\motorcycle.*                                    STI\
move POOL\071-bateau_boat.*                               STI\
move POOL\jeep.*                                          STI\
move POOL\basketballhoop01.*                              STI\
move POOL\bookshelf.*                                     STI\
move POOL\boxtruck.*                                      STI\
move POOL\bulldozer.*                                     STI\
move POOL\cannon.*                                        STI\
move POOL\ceilingfan01.*                                  STI\
move POOL\cementtruck.*                                   STI\
move POOL\cessna.*                                        STI\
move POOL\column.*                                        STI\
move POOL\convertible.*                                   STI\
move POOL\desk02.*                                        STI\
move POOL\dumptruck.*                                     STI\
move POOL\fighterjet.*                                    STI\
move POOL\filingcabinet.*                                 STI\
move POOL\firtree.*                                       STI\
move POOL\helicopter.*                                    STI\
move POOL\lawnmowertractor.*                              STI\
move POOL\mailtruck.*                                     STI\
move POOL\motorboat02.*                                   STI\
move POOL\photocopier.*                                   STI\
move POOL\pingpongtable.*                                 STI\
move POOL\steamroller.*                                   STI\
move POOL\tank.*                                          STI\
move POOL\tankertruck.*                                   STI\
move POOL\tractor.*                                       STI\
move POOL\tree.*                                          STI\
move POOL\020-baignoire_bathtub_r.*                       STI\
move POOL\couch_r.*                                         STI\
move POOL\rocker_r.*                                        STI\
move POOL\178-locomotive_locomotive_r.*                   STI\
move POOL\008-ambulance_ambulance_r.*                     STI\
move POOL\064-camping-car_camper_r.*                      STI\
move POOL\018-car_bus_r.*                                 STI\
move POOL\car_r.*                                           STI\
move POOL\piano_r.*                                         STI\
move POOL\truck_r.*                                         STI\
move POOL\plane_r.*                                         STI\
move POOL\motorcycle_r.*                                  STI\
move POOL\071-bateau_boat_r.*                             STI\
move POOL\jeep_r.*                                        STI\
move POOL\basketballhoop01_r.*                            STI\
move POOL\bookshelf_r.*                                   STI\
move POOL\boxtruck_r.*                                    STI\
move POOL\bulldozer_r.*                                   STI\
move POOL\cannon_r.*                                      STI\
move POOL\ceilingfan01_r.*                                STI\
move POOL\cementtruck_r.*                                 STI\
move POOL\cessna_r.*                                      STI\
move POOL\column_r.*                                      STI\
move POOL\convertible_r.*                                 STI\
move POOL\desk02_r.*                                      STI\
move POOL\dumptruck_r.*                                   STI\
move POOL\fighterjet_r.*                                  STI\
move POOL\filingcabinet_r.*                               STI\
move POOL\firtree_r.*                                     STI\
move POOL\helicopter_r.*                                  STI\
move POOL\lawnmowertractor_r.*                            STI\
move POOL\mailtruck_r.*                                   STI\
move POOL\motorboat02_r.*                                 STI\
move POOL\photocopier_r.*                                 STI\
move POOL\pingpongtable_r.*                               STI\
move POOL\steamroller_r.*                                 STI\
move POOL\tank_r.*                                        STI\
move POOL\tankertruck_r.*                                 STI\
move POOL\tractor_r.*                                     STI\
move POOL\tree_r.*                                        STI\
move POOL\badmintonracket.*                               STI\
move POOL\butterknife.*                                   STI\
move POOL\candycane01a.*                                  STI\
move POOL\daisy.*                                         STI\
move POOL\funnel.*                                        STI\
move POOL\jeans01.*                                       STI\
move POOL\visor.*                                         STI\
move POOL\beerbottle.*                                    STI\
move POOL\branch02.*                                        STI\
move POOL\brusselssprout.*                                  STI\
move POOL\carrot01.*                                        STI\
move POOL\clipboard.*                                       STI\
move POOL\dustpan.*                                         STI\
move POOL\gluetube.*                                        STI\
move POOL\interlockingbuildingblock03b.*                    STI\
move POOL\keychain.*                                        STI\
move POOL\leek.*                                            STI\
move POOL\measuringspoon.*                                  STI\
move POOL\mitten04.*                                        STI\
move POOL\nail.*                                            STI\
move POOL\pictureframe04.*                                  STI\
move POOL\seashell01.*                                      STI\
move POOL\stapler03a.*                                      STI\
move POOL\tongs01b.*                                        STI\
move POOL\toydinosaur.*                                     STI\
move POOL\242-pot_jar.*                                   STI\
move POOL\fork.*                                            STI\
move POOL\hat.*                                             STI\
move POOL\shoe.*                                            STI\
move POOL\cornhusk.*                                      STI\
move POOL\007-allumette_match.*                           STI\
move POOL\053-briquet_lighter.*                           STI\
move POOL\059-cahier_exercice-book.*                      STI\
move POOL\075-carte_playing-card.*                        STI\
move POOL\089-chronometre_stop-watch.*                    STI\
move POOL\126-eprouvette_test-tube.*                      STI\
move POOL\248-quille_skittle.*                            STI\
move POOL\fishingrod.*                                    STI\
move POOL\razor01.*                                         STI\
move POOL\waterbottle01b.*                                  STI\
move POOL\badmintonracket_r.*                             STI\
move POOL\butterknife_r.*                                 STI\
move POOL\candycane01a_r.*                                STI\
move POOL\daisy_r.*                                       STI\
move POOL\funnel_r.*                                      STI\
move POOL\jeans01_r.*                                     STI\
move POOL\visor_r.*                                       STI\
move POOL\beerbottle_r.*                                  STI\
move POOL\branch02_r.*                                      STI\
move POOL\brusselssprout_r.*                                STI\
move POOL\carrot01_r.*                                      STI\
move POOL\clipboard_r.*                                     STI\
move POOL\dustpan_r.*                                       STI\
move POOL\gluetube_r.*                                      STI\
move POOL\interlockingbuildingblock03b_r.*                  STI\
move POOL\keychain_r.*                                      STI\
move POOL\leek_r.*                                          STI\
move POOL\measuringspoon_r.*                                STI\
move POOL\mitten04_r.*                                      STI\
move POOL\nail_r.*                                          STI\
move POOL\pictureframe04_r.*                                STI\
move POOL\seashell01_r.*                                    STI\
move POOL\stapler03a_r.*                                    STI\
move POOL\tongs01b_r.*                                      STI\
move POOL\toydinosaur_r.*                                   STI\
move POOL\242-pot_jar_r.*                                 STI\
move POOL\fork_r.*                                          STI\
move POOL\hat_r.*                                           STI\
move POOL\shoe_r.*                                          STI\
move POOL\cornhusk_r.*                                    STI\
move POOL\007-allumette_match_r.*                         STI\
move POOL\053-briquet_lighter_r.*                         STI\
move POOL\059-cahier_exercice-book_r.*                    STI\
move POOL\075-carte_playing-card_r.*                      STI\
move POOL\089-chronometre_stop-watch_r.*                  STI\
move POOL\126-eprouvette_test-tube_r.*                    STI\
move POOL\248-quille_skittle_r.*                          STI\
move POOL\fishingrod_r.*                                  STI\
move POOL\razor01_r.*                                       STI\
move POOL\waterbottle01b_r.*                                STI\